server:
  port: 8761
  address: 192.168.40.62

# eureka configuration not register microservices by default false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost